### ISSUE TITLE
Dual interface potentially crashing server (IllegalArgumentException)

### ISSUE THREAD

**Issue by dacioromero** [phantamanta44/ae2-fluid-crafting#11]
I have a server running All the Mods 6.0.0 with:

- AE2 Fluid Crafting 1.0.9
- Just Enough Energistics 1.0.8
- Gas Conduits 1.2.3
- SpongeForge 7.3.0
- CatClearLag 0.9.5.1

I have a dual interface on a magma crucible for auto-crafting and one for a small subnet used to access water and lava from the main network and pipe obsidian back.

I can provide a world file if it helps.

https://mcpaste.io/70ba62be53e431c2

[crash-2021-01-20_23.09.57-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/5846658/crash-2021-01-20_23.09.57-server.txt)

https://mcpaste.io/3ef85c9dbdab7cff

[crash-2021-01-21_03.16.22-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/5846653/crash-2021-01-21_03.16.22-server.txt)

**Comment by Yefancy** [comment]
Does it always be crashing? Is there a process to reproduce it?

**Comment by Yefancy** [comment]
I probably have some ideas and will try to fix it later

**Comment by dacioromero** [comment]
To be honest, I'm not entirely certain what causes it, but it's not a constant crash. Often I'll be somewhere else and then it happens. If it crashes again I'll try to reason what might've caused it

**Comment by Yefancy** [comment]
yeah, thx

**Comment by dacioromero** [comment]
So it happened again. I was connecting a subnetwork with quartz fiber and some other dual interface crashed the server. It seems to have something to do with power, but I don't really understand how AE2's power works internally. I'll add some more dense power cells to see if that helps at all

https://mcpaste.io/6ae351ceced8023c

[crash-2021-02-24_03.45.10-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6033242/crash-2021-02-24_03.45.10-server.txt)

EDIT: I think it was caused by the network running out of power

**Comment by Yefancy** [comment]
now pretty sure it was caused by the network running out of power. but I can't reproduce this in any way. I think it might have something to do with other mods or configurations. It would be nice to have your modpack and save of this bug.

**Comment by jkieberking** [comment]
we added ae2-fc to omnifactory on our server and we seem to be getting the same error:
```
Description: Exception in server tick loop

java.lang.IllegalStateException: java.lang.IllegalArgumentException: java.lang.ClassCastException@5f3293bc
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:201)
```
[crash-2021-04-23_19.12.57-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368463/crash-2021-04-23_19.12.57-server.txt)
[crash-2021-04-23_20.06.21-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368464/crash-2021-04-23_20.06.21-server.txt)
[crash-2021-04-23_21.26.00-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368465/crash-2021-04-23_21.26.00-server.txt)
[crash-2021-04-23_22.30.12-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368466/crash-2021-04-23_22.30.12-server.txt)
[crash-2021-04-23_22.55.05-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368467/crash-2021-04-23_22.55.05-server.txt)
[crash-2021-04-23_04.23.02-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368468/crash-2021-04-23_04.23.02-server.txt)
[crash-2021-04-23_14.13.39-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368469/crash-2021-04-23_14.13.39-server.txt)
[crash-2021-04-23_16.46.35-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368470/crash-2021-04-23_16.46.35-server.txt)
[crash-2021-04-23_17.29.33-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6368471/crash-2021-04-23_17.29.33-server.txt)

here's a copy of our world: https://drive.google.com/file/d/19PFkwN0eiqYeJPE9R9IwF1usszewFMma/view?usp=sharing

![image](https://user-images.githubusercontent.com/29125096/115938296-2046d880-a468-11eb-8d87-cb4cff522087.png)

here's the omnifactory profile

main ae2 terminal is at
x: `171`
z: `264`
y: `102`

**Comment by jkieberking** [comment]
tried the fix you posted here: https://github.com/Gregicality/gregicality-skyblock-edition/issues/15#issuecomment-787374682 and the error still happens 😢 

[crash-2021-04-24_14.22.13-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6369787/crash-2021-04-24_14.22.13-server.txt)

**Comment by Yefancy** [comment]
> tried the fix you posted here: [Gregicality/gregicality-skyblock-edition#15 (comment)](https://github.com/Gregicality/gregicality-skyblock-edition/issues/15#issuecomment-787374682) and the error still happens 😢
> 
> [crash-2021-04-24_14.22.13-server.txt](https://github.com/phantamanta44/ae2-fluid-crafting/files/6369787/crash-2021-04-24_14.22.13-server.txt)

yeah, i konw. I'm going to reproduce the bug based on your world, do you have any process to guide me?

**Comment by jkieberking** [comment]
https://drive.google.com/file/d/1_G6v37fmZGjM_0_DRdi_acrcubQ_DEcQ/view?usp=sharing

can reproduce the crash by making the capacitor bank in our base run out of energy (should happen when tree farm runs)

the end of the clip is minecraft crashing

**Comment by Aelrath** [comment]
As above users we also added your mod to our Omnifactory server (your mod is absolutely amazing). We started having crashes last week and through the stacktrace saw it was AE2 power related so we just decided to remove all our Dense Energy Cells and give both of us a creative one to try prevent the energy grid crash (that from our numerous crashes last week seemed to be when our energy cells charged / discharged / lost power).

We also together with the creative energy cell set the following config D:UsageMultiplier=0.0 in the AE2 config file. This seemed to work until this weekend when while breaking an AE2 cable it crashed again (same stacktrace issue - guess it caused an energu update tick on the grid when cable broke ). This morning while both of use were offline (but my friend had some long processing crafting going) the bottom crash happened. 

I now set the D:ForgeEnergy=0.0 and D:IC2=0.0 to see if that will help. Will update on further crashes.


--- Crash Log ---

[03:23:12] [Server thread/ERROR] [AE2:S]: [AppEng] Network Event caused exception:
[03:23:12] [Server thread/ERROR] [AE2:S]: Class: xyz.phanta.ae2fc.tile.TileDualInterface, Object: xyz.phanta.ae2fc.tile.TileDualInterface@760cb9b3
[03:23:12] [Server thread/INFO] [AE2:S]: Exception: 
java.lang.IllegalArgumentException: java.lang.ClassCastException@ef44d4d
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:194) [NetworkEventBus$EventMethod.class:?]
	at appeng.me.NetworkEventBus$EventMethod.access$400(NetworkEventBus.java:176) [NetworkEventBus$EventMethod.class:?]
	at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:225) [NetworkEventBus$MENetworkEventInfo.class:?]
	at appeng.me.NetworkEventBus$MENetworkEventInfo.access$200(NetworkEventBus.java:211) [NetworkEventBus$MENetworkEventInfo.class:?]
	at appeng.me.NetworkEventBus.postEvent(NetworkEventBus.java:129) [NetworkEventBus.class:?]
	at appeng.me.Grid.postEvent(Grid.java:222) [Grid.class:?]
	at appeng.me.cache.EnergyGridCache.publicPowerState(EnergyGridCache.java:277) [EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.access$500(EnergyGridCache.java:63) [EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache$GridPowerStorage.removeCurrentAEPower(EnergyGridCache.java:685) [EnergyGridCache$GridPowerStorage.class:?]
	at appeng.me.cache.EnergyGridCache$GridPowerStorage.extractAEPower(EnergyGridCache.java:620) [EnergyGridCache$GridPowerStorage.class:?]
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:311) [EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248) [EnergyGridCache.class:?]
	at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:674) [CraftingCPUCluster.class:?]
	at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:617) [CraftingCPUCluster.class:?]
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:152) [CraftingGridCache.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) [GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) [Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228) [TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_929_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[03:23:12] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@5e6686bc:
java.lang.IllegalStateException: java.lang.IllegalArgumentException: java.lang.ClassCastException@ef44d4d
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:201) ~[NetworkEventBus$EventMethod.class:?]
	at appeng.me.NetworkEventBus$EventMethod.access$400(NetworkEventBus.java:176) ~[NetworkEventBus$EventMethod.class:?]
	at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:225) ~[NetworkEventBus$MENetworkEventInfo.class:?]
	at appeng.me.NetworkEventBus$MENetworkEventInfo.access$200(NetworkEventBus.java:211) ~[NetworkEventBus$MENetworkEventInfo.class:?]
	at appeng.me.NetworkEventBus.postEvent(NetworkEventBus.java:129) ~[NetworkEventBus.class:?]
	at appeng.me.Grid.postEvent(Grid.java:222) ~[Grid.class:?]
	at appeng.me.cache.EnergyGridCache.publicPowerState(EnergyGridCache.java:277) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.access$500(EnergyGridCache.java:63) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache$GridPowerStorage.removeCurrentAEPower(EnergyGridCache.java:685) ~[EnergyGridCache$GridPowerStorage.class:?]
	at appeng.me.cache.EnergyGridCache$GridPowerStorage.extractAEPower(EnergyGridCache.java:620) ~[EnergyGridCache$GridPowerStorage.class:?]
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:311) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248) ~[EnergyGridCache.class:?]
	at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:674) ~[CraftingCPUCluster.class:?]
	at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:617) ~[CraftingCPUCluster.class:?]
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:152) ~[CraftingGridCache.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_929_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@ef44d4d
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:194) ~[NetworkEventBus$EventMethod.class:?]
	... 24 more
